name: day_plan_diary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.8
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  go_router: ^9.0.0
  provider: ^6.1.2
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:
  shared_preferences: ^2.1.1

flutter:


  uses-material-design: true

