name: day_plan_diary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.8
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  go_router: ^9.0.0
  provider: ^6.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.3
  google_sign_in: ^6.2.2
  connectivity_plus: ^4.0.1
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  timezone: ^0.10.0
  google_api_availability: ^5.0.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.0.0
  grpc: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:

flutter:
  assets:
    - assets/images/splash_image.png

  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_image.png
  android: true
  ios: true
  web: false


